### ISSUE TITLE
如何编译该文档生成网站

### ISSUE THREAD

**Issue by QunWei-L** [apachecn/kafka-doc-zh#12]
请教一下:

把zip包下载到本地后, 直接打开index.html等页面, 好像不太对

不知道正确的使用姿势是 ?

**Comment by mikechengwei** [comment]
官方文档中用的是c#中的ASP模板渲染的。所以我写了一个前端渲染的脚本。
具体步骤：

1. 你要安装好node
2. 安装 gulp
    * npm install -g cnpm --registry=https://registry.npm.taobao.org
    * npm install -g gulp
3. 然后执行gulp， 会把所有html输出到dist目录下。

你可以参考gulp.js脚本

**Comment by mikechengwei** [comment]
@QunWei-L

**Comment by QunWei-L** [comment]
get, 感谢

**Comment by jiangzhonglian** [comment]
$ cd ~/kafka-doc-zh/doc/1.0.0

$ node -v
v16.13.0

$ gulp --version
CLI version: 2.3.0
Local version: 4.0.2

(npm install -save-dev gulp@4)

结果所有html输出到dist目录下
$ gulp
