### ISSUE TITLE
Kafka 2.1 version 翻译进度

### ISSUE THREAD

**Issue by mikechengwei** [apachecn/kafka-doc-zh#73]
基于 [kafka 1.0 version 翻译版本](kafka.apachecn.org) 翻译版本 优化出 2.1 版本
留言格式：昵称 + QQ + 章节
翻译时间:   3.15-3.31
联系方式:  QQ 842725815

| 章节  | 译者  | 进度 |
|:------------- |:---------------:| -------------:|
| [1.1 Introduction](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/introduction.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [1.2 Use Cases](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/uses.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [1.3 Quick Start](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/quickstart.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [1.4 Ecosystem](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ecosystem.html)|| |
| [1.5 Upgrading](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/upgrade.html)|| |
| [2.1 Producer API](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/api.html)|| |
|[ 2.2 Consumer API](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/api.html)|| |
| [2.3 Streams API](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/api.html)|| |
| [3.1 Broker Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/configuration.html)|| |
| [3.2 Topic Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/configuration.html)|| |
| [3.3 Producer Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/configuration.html)|| |
| [3.4 Consumer Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/configuration.html)|| |
| [3.5 Kafka Connect Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/configuration.html)|| |
| [3.6 Kafka Streams Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/configuration.html)|| |
| [3.7 AdminClient Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/configuration.html)|| |
| [4.1 Motivation](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.2 Persistence](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.3 Efficiency](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.4 The Producer](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.5 The Consumer](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.6 Message Delivery Semantics](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.7 Replication](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.8 Log Compaction](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [4.9 Quotas](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/design.html)|[mikechengwei](https://github.com/mikechengwei)| |
| [5.1 Network Layer](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/implementation.html)|| |
| [5.2 Messages](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/implementation.html)|| |
| [5.3 Message format](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/implementation.html)|| |
| [5.4 Log](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/implementation.html)|| |
| [5.5 Distribution](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/implementation.html)|| |
| [6.1 Basic Kafka Operations](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ops.html)|| |
| [6.2 Datacenters](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ops.html)|| |
| [6.3 Important Configs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ops.html)|| |
| [6.4 Java Version](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ops.html)|| |
| [6.5 Hardware and OS](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ops.html)|| |
| [6.6 Monitoring](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ops.html)|| |
| [6.7 ZooKeeper](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/ops.html)|| |
| [7.1 Security Overview](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/security.html)|| |
| [7.2 Encryption and Authentication using SSL](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/security.html)|| |
| [7.3 Authentication using SASL](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/security.html)|| |
| [7.4 Authorization and ACLs](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/security.html)|| |
| [7.5 Incorporating Security Features in a Running Cluster](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/security.html)|| |
| [7.6 ZooKeeper Authentication](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/security.html)|| |
| [8.1 Overview](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/connect.html)|| |
|[ 8.2 User Guide](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/connect.html)|| |
| [8.3 Connector Development Guide](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/connect.html)|| |
| [9.1 Play with a Streams Application](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/streams/quickstart.html)|| |
| [9.2 Write your own Streams Applications](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/streams/tutorial.html)|| |
| [9.3 Developer Manual](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/streams/developer-guide/index.html)|| |
| [9.4 Core Concepts](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/streams/core-concepts.html)|| |
| [9.5 Architecture](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/streams/architecture.html)|| |
| [9.6 Upgrade Guide](https://github.com/apachecn/kafka-doc-zh/blob/2.2.0/doc/2.2.0/22/streams/upgrade-guide.html)|| |

**Comment by lubeijia** [comment]
woodman+2.X+987111031

**Comment by MeiJinYuan** [comment]
Grady +3.2 Topic Configs+974751615

**Comment by Abel-Huang** [comment]
请问现在这个翻译活动已经已经结束了么

**Comment by jiangzhonglian** [comment]
> 请问现在这个翻译活动已经已经结束了么

没有没有，持续翻译

**Comment by HiMindTheGaps** [comment]
现在翻译活动还在进行吗

**Comment by mikechengwei** [comment]
不进行啦
