### ISSUE TITLE
http://kafka.apachecn.org/地址打开内容有问题啊

### ISSUE THREAD

**Issue by sanpo** [apachecn/kafka-doc-zh#83]
恭喜您，LNMP一键安装包安装成功！

**Comment by woodliu** [comment]
没人管了吗

**Comment by mikechengwei** [comment]
@woodliu 不好意思 我问问

**Comment by mikechengwei** [comment]
@jiangzhonglian @wizardforcel 能否解决下

**Comment by jiangzhonglian** [comment]
谢谢提醒哈，看到了，正在处理

**Comment by jiangzhonglian** [comment]
已经恢复了，谢谢

**Comment by woodliu** [comment]
@jiangzhonglian 好像没有好哇，麻烦check下

**Comment by jiangzhonglian** [comment]
![image](https://user-images.githubusercontent.com/9199175/62853362-b1baf900-bd1e-11e9-9574-bd4022842726.png)
